// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package json

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4086215fDecodeXxxApiHubV1Json(in *jlexer.Lexer, out *ExchangeKeyResp) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "server_pub_key":
			if in.IsNull() {
				in.Skip()
			} else {
				copy(out.ServerPubKey[:], in.Bytes())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4086215fEncodeXxxApiHubV1Json(out *jwriter.Writer, in ExchangeKeyResp) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"server_pub_key\":"
		out.RawString(prefix[1:])
		out.Base64Bytes(in.ServerPubKey[:])
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ExchangeKeyResp) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4086215fEncodeXxxApiHubV1Json(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ExchangeKeyResp) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4086215fEncodeXxxApiHubV1Json(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ExchangeKeyResp) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4086215fDecodeXxxApiHubV1Json(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ExchangeKeyResp) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4086215fDecodeXxxApiHubV1Json(l, v)
}
func easyjson4086215fDecodeXxxApiHubV1Json1(in *jlexer.Lexer, out *ExchangeKeyReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "device_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DeviceID = uint64(in.Uint64())
			}
		case "client_pub_key":
			if in.IsNull() {
				in.Skip()
			} else {
				copy(out.ClientPubKey[:], in.Bytes())
			}
		case "client_hmac_key":
			if in.IsNull() {
				in.Skip()
			} else {
				copy(out.ClientHmacKey[:], in.Bytes())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4086215fEncodeXxxApiHubV1Json1(out *jwriter.Writer, in ExchangeKeyReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"device_id\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.DeviceID))
	}
	{
		const prefix string = ",\"client_pub_key\":"
		out.RawString(prefix)
		out.Base64Bytes(in.ClientPubKey[:])
	}
	{
		const prefix string = ",\"client_hmac_key\":"
		out.RawString(prefix)
		out.Base64Bytes(in.ClientHmacKey[:])
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ExchangeKeyReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4086215fEncodeXxxApiHubV1Json1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ExchangeKeyReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4086215fEncodeXxxApiHubV1Json1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ExchangeKeyReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4086215fDecodeXxxApiHubV1Json1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ExchangeKeyReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4086215fDecodeXxxApiHubV1Json1(l, v)
}
